<?php
$config_path_backup =	'c:\\www.classaxe.com\\dx\\ndb\\log\\steve\\';	// Absolute path for backup files (PC-Type)
//$config_path_backup =	'/home/classaxe/www/dx/ndb/log/steve/';		// Absolute path for backup files (UNIX-Type - CHOWN this to PHP UNIX user)

$config_db_host =	'localhost';				// Name of your DB Host (normally localhost)
$config_db_name =	'ndb-steve';				// Name of your mySQL DB
$config_db_pass =	'steve123';				// Password of your mySQL DB account
$config_db_user =	'ndb-steve';				// Name of your mySQL DB account

$config_qth_lat =	45.6103;
$config_qth_lon =	-117.9358;
?>
