// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      config.js                                            *
// * Generated by:  RWW                                                  *
// *                                                                     *
// * This is a user editable file with details on the logbook's owner.   *
// ***********************************************************************

qth_lat =    -17.9792;
qth_lon =    122.208;
qth_name =   "Martin Francis, Broome (Remote), WE, AUS";
qth_email =  "martin@classaxe.com";
qth_home =   "";
monthly =    1;
utc_offset = -8;
