// ***********************************************************************
// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      config.js                                            *
// * Generated by:  RNA                                                  *
// *                                                                     *
// * This is a user editable file with details on the logbook's owner.   *
// ***********************************************************************

qth_lat =    43.6875;
qth_lon =    -79.7917;
qth_name =   "Vernon Matheson, Brampton, ON, CAN";
qth_email =  "vmath@sympatico.ca";
qth_home =   "";
monthly =    1;
utc_offset = -5;
