// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      stations.js                                          *
// * Generated by:  RNA                                                  *
// *                                                                     *
// * This is a user editable file containing actual log data.            *
// *                                                                     *
// * Put station details in the following format:                        *
// * STATION(khz,call,qth,ste,cnt,cyc,daid,lsb,usb,pwr,lat,lon,notes);   *
// *                                                                     *
// * Each field should be enclosed with quotes and set to "" if unknown. *
// * For any given beacon:                                               *
// *   KHz     is the frequency of the carrier;                          *
// *   call    is the callsign -                                         *
// *           Indicate DGPS Idents with # before station ident number   *
// *   qth     is the town in which the beacon is located;               *
// *   ste     is the state or province abbreviation (eg MI = Michigan)  *
// *           or "" if not applicable (e.g. Bahamas)                    *
// *   cnt     is the NDB List approved country code;                    *
// *   cyc     is the number of seconds between repetitions of the call  *
// *   daid    stands for 'Dash after ID' and is either "Y" or "N"       *
// *   lsb     is the offset of the lower sideband from the carrier      *
// *           (Note Canadian NDBs are USB only, for these set to "")    *
// *   usb     is the offset of the upper sideband from the carrier      *
// *   pwr     is the power in watts of the transmitter                  *
// *   lat     is the decimal latitude value (S values are negative)     *
// *   lon     is the decimal longitude value (W values are negative)    *
// *   notes   These notes will show with each logging of the station.   *
// ***********************************************************************

STATION ("198","DIW","Dixon","NC","USA","10.0","N","1050","1038","2000","34.5625","-77.4583","");
STATION ("201","GL","La Grande Riviere","QC","CAN","10.3","Y","","411","500","53.6458","-77.7083","");
STATION ("201","YKX","Kirkland Lake","ON","CAN","10.3","Y","","407","200","48.2292","-79.875","");
STATION ("201","ZXU","London","ON","CAN","10.5","Y","","986","","42.9792","-81.125","Was U-201; rptd IDing \'U\' after change (backup TX?)");
STATION ("204","GB","Greater Buffalo / Plazz","NY","USA","8.5","N","1020","1020","","42.8542","-78.7917","");
STATION ("205","XZ","Wawa","ON","CAN","10.2","Y","","405","125","48.0208","-84.7083","");
STATION ("206","GLS","Galveston","TX","USA","10.0","N","1020","1020","2000","29.3542","-94.7917","");
STATION ("206","QI","Yarmouth","NS","CAN","10.2","Y","","409","500","43.8125","-66.125","");
STATION ("207","FD","Brantford","ON","CAN","10.5","Y","","392","","43.0625","-80.375","");
STATION ("208","YSK","Sanikiluaq","NU","CAN","","Y","","410","400","56.5208","-79.2083","");
STATION ("209","GDW","Gladwin / Wiggins","MI","USA","","N","","1008","25","43.9792","-84.4583","");
STATION ("209","MT","Chiboo","QC","CAN","10.3","Y","","406","500","49.8125","-74.4583","");
STATION ("212","TS","Timmins","ON","CAN","9.8","Y","","414","400","48.5625","-81.4583","");
STATION ("215","YTR","Trenton","ON","CAN","","Y","1039","1002","25","44.1875","-77.375","");
STATION ("216","CLB","Carolina Beach","NC","USA","","N","1020","1020","","34.1042","-77.9583","");
STATION ("216","YFA","Fort Albany","ON","CAN","","Y","","405","200","52.1875","-81.7083","");
STATION ("218","RL","Red Lake","ON","CAN","9.7","Y","","410","1000","51.0625","-93.7917","117\' vert.");
STATION ("218","YUY","Rouyn","QC","CAN","","Y","","400","500","48.1875","-78.9583","");
STATION ("219","YMG","Manitouwadge","ON","CAN","","Y","","400","100","49.0625","-85.875","");
STATION ("220","BX","Blanc Sablon","QC","CAN","","Y","","400","2000","51.4375","-57.2083","");
STATION ("221","HM","Hamilton","ON","CAN","10.5","Y","","375","25","43.1042","-80.0417","");
STATION ("223","YYW","Armstrong","ON","CAN","10.5","Y","","400","100","50.3125","-89.0417","");
STATION ("224","MO","Moosonee","ON","CAN","10.3","Y","","405","400","51.2708","-80.625","");
STATION ("230","QB","Quebec","QC","CAN","10.4","Y","","407","500","46.7292","-71.4583","");
STATION ("231","BU","Klump","NY","USA","","N","1023","1016","","43.0208","-78.625","");
STATION ("233","QN","Nakina","ON","CAN","10.2","Y","","408","400","50.1875","-86.625","");
STATION ("236","ZLB","Toronto","ON","CAN","10.5","Y","","382","","43.6042","-79.7083","Was J-236");
STATION ("239","TCU","Tecumseh","MI","USA","","N","1025","1025","","42.0208","-83.875","");
STATION ("239","VO","Val D' Or","QC","CAN","10.3","Y","","408","500","48.0625","-77.7917","");
STATION ("241","HF","Hearst / Rene Fontaine","ON","CAN","","Y","","410","100","49.6875","-83.7083","");
STATION ("242","YMY","Ear Falls","ON","CAN","10.5","Y","","423","50","50.7292","-93.375","");
STATION ("243","YVB","Bonaventure","QC","CAN","","Y","","413","90","48.1042","-65.5417","");
STATION ("244","DG","Chute Des Passes","QC","CAN","","Y","","410","500","49.8958","-71.2917","");
STATION ("245","YZE","Gore Bay","ON","CAN","","Y","","400","400","45.9375","-82.625","");
STATION ("246","DFI","Defiance","OH","USA","","N","1040","1020","","41.3542","-84.4583","");
STATION ("247","YLH","Lansdowne House","ON","CAN","","Y","","410","250","52.1875","-87.9583","");
STATION ("248","FRT","Fairmont","SC","USA","","N","1000","1030","400","34.8958","-81.9583","");
STATION ("248","KZ","Buttonville","ON","CAN","","Y","","390","25","43.9375","-79.2917","");
STATION ("248","UL","Montreal","QC","CAN","","Y","","400","1000","45.4792","-73.875","");
STATION ("248","WG","Winnipeg","MB","CAN","6.29/10.43","Y","415","400","250","49.8958","-97.375","+1230 Hz rptd");
STATION ("250","YTJ","Terrace Bay","ON","CAN","","Y","409","405","100","48.8125","-87.125","");
STATION ("257","SQT","Satellite","FL","USA","","N","1040","1040","","28.1042","-80.7083","");
STATION ("257","TZ","Gibraltar Point","ON","CAN","","Y","","381","25","43.6042","-79.375","");
STATION ("257","YXR","Earlton","ON","CAN","","Y","","380","400","47.7292","-79.7917","");
STATION ("258","ORJ","Corry","PA","USA","","N","","1016","25","41.8958","-79.625","2nd ID of each pair very poorly keyed");
STATION ("258","ZSJ","Sandy Lake","ON","CAN","10.1","Y","","408","500","53.0625","-93.375","1kW rptd; 150\' vertical");
STATION ("260","BYN","Bryan","OH","USA","","N","1020","1023","","41.4792","-84.4583","");
STATION ("260","UFX","St. Felix De Valois","QC","CAN","","Y","","398","25","46.1875","-73.4583","");
STATION ("260","YAT","Attawapiskat","ON","CAN","","Y","412","410","125","52.9375","-82.4583","");
STATION ("261","2H","Lebel Sur Quevillon","QC","CAN","","Y","1000","1000","125","49.0208","-77.0417","");
STATION ("261","GD","Goderich","ON","CAN","","Y","","375","","43.7292","-81.7083","");
STATION ("263","YGK","Kangiqsujuaq","ON","CAN","","Y","","401","1000","44.3125","-76.625","");
STATION ("263","ZTS","Sandy Falls / Timmins","ON","CAN","","Y","","400","","48.4792","-81.375","Rptd \'Seriously wrong\' by A Robins 2004-01-02 - offset 290!");
STATION ("266","ZHM","Hamilton","ON","CAN","","Y","","350","50","43.1458","-79.7917","Was B-266");
STATION ("268","S7","Hanover","ON","CAN","","Y","","1035","100","44.1458","-81.0417","USB only for this private beacon");
STATION ("272","YQA","Muskoka","ON","CAN","","Y","","405","400","45.0208","-79.2917","");
STATION ("273","ZV","Sept Iles","QC","CAN","","Y","","397","500","50.1875","-66.125","");
STATION ("274","YPM","Pikangikum","ON","CAN","","Y","","375","25","51.8125","-93.9583","");
STATION ("276","YEL","Elliot Lake","ON","CAN","","Y","411","411","250","46.3542","-82.625","100\' vertical");
STATION ("278","ADG","Adrian","MI","USA","","N","1030","1020","","41.8542","-84.0417","");
STATION ("278","FKR","Frankfort","IN","USA","","N","1020","1023","25","40.2708","-86.5417","-1020 Hz rptd");
STATION ("278","NM","Matagami","QC","CAN","","Y","","406","400","49.7292","-77.7083","500w rptd, vertical");
STATION ("283","PT","Pelee Island","ON","CAN","10.5","Y","","405","100","41.7708","-82.7083","");
STATION ("284","QD","The Pas","MB","CAN","9.8","Y","","406","500","53.9792","-101.042","");
STATION ("286","ZSM","Gros Cap","ON","CAN","","Y","1030","375","100","46.5208","-84.625","");
STATION ("289","YLQ","La Tuque","QC","CAN","","Y","","392","500","47.3958","-72.7917","");
STATION ("291","9Q","Amos","QC","CAN","","Y","","370","25","48.5625","-78.2083","");
STATION ("300","YOG","Ogoki Post","ON","CAN","","Y","","405","25","51.6458","-85.875","Rptd stby TX 2003-11-07 (Alex Wiecek)");
STATION ("303","YPP","Parent Que","QC","CAN","9.8","Y","","400","1000","47.8958","-74.7083","");
STATION ("305","YQ","Churchill","MB","CAN","10.3","Y","","404","500","58.7708","-93.9583","300\' vertical");
STATION ("317","ZMX","Janvier / Mirabel","QC","CAN","10.0","Y","","420","200","45.7292","-73.9583","");
STATION ("317","ZZR","Trenton","ON","CAN","","Y","1045","1013","50","44.0625","-77.625","Formerly \'R\'");
STATION ("323","UWP","Argentia","NL","CAN","","Y","","400","1000","47.3125","-53.9583","");
STATION ("326","VV","Wiarton","ON","CAN","9.8","Y","","375","400","44.6875","-81.2083","");
STATION ("326","YQK","Kenora","ON","CAN","9.7","Y","","400","200","49.8125","-94.4583","");
STATION ("328","YTL","Big Trout Lake","ON","CAN","10.4","Y","","404","1000","53.8125","-89.875","");
STATION ("329","CH","Ashly","SC","USA","","N","1040","1025","400","32.9792","-80.125","");
STATION ("329","YHN","Hornepayne","ON","CAN","","Y","","409","500","49.2292","-84.625","+500Hz rptd");
STATION ("332","QT","Thunder Bay","ON","CAN","6.48/10.3","Y","","400","1000","48.3542","-89.4583","");
STATION ("332","YFM","La Grand 4","QC","CAN","","Y","","403","2000","53.7292","-73.7083","");
STATION ("334","YSH","Smiths Falls","ON","CAN","","Y","","405","25","44.8958","-76.0417","");
STATION ("335","YLD","Chapleau","ON","CAN","10.4","Y","","405","100","47.7708","-83.375","");
STATION ("335","ZKF","Kitchener","ON","CAN","","Y","","385","25","43.4792","-80.2917","");
STATION ("336","BV","Champlain","QC","CAN","","Y","","410","25","46.8542","-71.2917","");
STATION ("338","DE","Detroit","MI","USA","","N","1015","1015","","42.4792","-83.125","");
STATION ("338","ZEM","Eastmain","QC","CAN","10.4","Y","","380","25","52.2292","-78.5417","");
STATION ("340","YY","Mont Joli","QC","CAN","10.3","Y","","398","500","48.5625","-68.2917","");
STATION ("341","CCJ","Clark Co","OH","USA","","N","1042","1000","","39.8542","-83.7917","Very slow, continuous ID");
STATION ("341","ZLP","Toronto","ON","CAN","10.1","Y","","401","40","43.6458","-79.7083","");
STATION ("344","AVN","Avon","NY","USA","8.5","N","1031","1035","","43.0208","-77.7917","");
STATION ("344","CL","Harri","OH","USA","","N","1039","1031","250","41.3542","-81.9583","");
STATION ("344","JA","Dinns","FL","USA","","N","1065","1020","400","30.4792","-81.7917","");
STATION ("344","YGV","Havre St Pierre","QC","CAN","10.4","Y","","398","25","50.2708","-63.625","");
STATION ("344","ZOW","Moody / Ottawa","ON","CAN","10.0","Y","404","402","40","45.2708","-75.7083","");
STATION ("346","JXT","Jefferson","TN","USA","","N","","1150","25","36.1042","-83.4583","");
STATION ("346","YXL","Sioux Lookout","ON","CAN","9.8","Y","","426","1000","50.1042","-91.875","");
STATION ("347","YG","Charlottetown","PE","CAN","10.2","Y","","405","1600","46.1875","-63.125","");
STATION ("348","ZUL","Rockland / Dorval","QC","CAN","10.0","Y","","425","100","45.5208","-73.625","+395 Hz rptd");
STATION ("349","APG","Aberdeen","MD","USA","","N","1045","1050","","39.5208","-76.125","");
STATION ("350","D7","Kincardine","ON","CAN","10.4","Y","400","390","25","44.1875","-81.625","");
STATION ("350","DF","Deer Lake","NL","CAN","","Y","","1020","1000","49.1875","-57.4583","");
STATION ("350","LE","Leevy","NC","USA","","N","1040","1000","400","35.9375","-78.7083","");
STATION ("350","ME","Deana","IL","USA","","N","1060","1018","400","41.9792","-88.0417","+1010 Hz rptd");
STATION ("350","RG","Gally","OK","USA","","N","1050","1020","","35.3125","-97.625","");
STATION ("351","YKQ","Waskaganish","QC","CAN","","Y","","400","500","51.4792","-78.7083","110\' vertical");
STATION ("353","JUK","Mc Kinnon","GA","USA","","N","","1044","25","31.1458","-81.375","");
STATION ("353","QG","Windsor","ON","CAN","","Y","400","380","25","42.3125","-82.875","400w rptd; 125\' vert");
STATION ("354","MKS","Moncks Corner","SC","USA","","N","","1010","25","33.1875","-80.0417","");
STATION ("355","YWP","Webequie","ON","CAN","","Y","","408","100","52.9792","-87.375","200w rptd; 110\' vertical");
STATION ("356","HEU","Hunter","NY","USA","","N","1031","1016","","42.8542","-73.9583","");
STATION ("356","PB","Rubin","FL","USA","","N","1035","1000","","26.6875","-80.2083","");
STATION ("356","UUV","Sullivan","MO","USA","","N","1035","1040","","38.2292","-91.125","");
STATION ("358","TNY","Kelso","TN","USA","","N","1025","1024","25","35.1458","-86.5417","");
STATION ("360","PN","Port Menier","QC","CAN","","Y","","400","500","49.8542","-64.375","");
STATION ("361","HB","Himun","NC","USA","","N","1000","1020","","35.9792","-79.625","");
STATION ("362","AK","Akron","OH","USA","","N","1055","1026","","41.0625","-81.375","");
STATION ("362","C7","Geraldton","ON","CAN","","Y","","405","250","49.7708","-86.9583","Rptd +800Hz (Jim Smith, 2004-11-01)");
STATION ("362","LYL","Lima","OH","USA","","N","1017","1000","25","40.6875","-84.0417","");
STATION ("362","SB","Sudbury","ON","CAN","","Y","405","395","400","46.6458","-80.9583","400W rptd; 125\' vertical");
STATION ("363","RNB","Rainbow","NJ","USA","","N","1060","1035","50","39.4375","-75.125","");
STATION ("364","TZ","Cogan","VA","USA","","N","","1070","","39.1042","-78.0417","");
STATION ("365","AA","Kenie / Fargo","ND","USA","6.8","N","1050","1020","100","47.0208","-96.7917","60\' \"T\"");
STATION ("365","TV","Traverse City","MI","USA","","N","1060","1026","30","44.7292","-85.4583","");
STATION ("366","YMW","Maniwaki","QC","CAN","","Y","","400","500","46.1875","-75.9583","");
STATION ("368","ZYZ","Toronto","ON","CAN","10.5","Y","","375","25","43.6042","-79.5417","");
STATION ("370","GR","Grindstone","QC","CAN","","Y","","390","25","47.3958","-61.875","");
STATION ("370","YBV","Berens River","MB","CAN","10.6","Y","400","370","50","52.3542","-97.0417","");
STATION ("371","GW","Jarpik","QC","CAN","","Y","","410","500","55.2708","-77.7917","Vertical");
STATION ("372","CQD","Cascade","PA","USA","","N","1051","1020","","42.1042","-80.125","");
STATION ("373","2Q","Mont-laurier","QC","CAN","8.0","Y","410","410","25","46.6042","-75.4583","");
STATION ("373","AEA","Jones","VA","USA","","N","","1020","","36.6042","-78.0417","");
STATION ("373","YXK","Rimouski","QC","CAN","","Y","","375","25","48.4792","-68.5417","");
STATION ("375","7B","St Thomas","ON","CAN","","Y","","1025","25","42.7708","-81.125","");
STATION ("376","LC","Pickl","OH","USA","","N","1050","1010","49","39.8958","-82.875","");
STATION ("376","YAG","Fort Frances","ON","CAN","10.8","Y","","394","40","48.6875","-93.5417","");
STATION ("376","ZIN","Great Inagua","","BAH","","N","1060","1025","400","20.9792","-73.7083","");
STATION ("377","YRR","Greely","ON","CAN","10.4","Y","","410","25","45.2708","-75.5417","");
STATION ("378","RJ","Roberval","QC","CAN","10.1","Y","","400","500","48.5625","-72.2917","");
STATION ("379","BRA","Broad River","NC","USA","","N","1020","1040","","35.2708","-82.4583","");
STATION ("379","YPQ","Peterborough","ON","CAN","10.4","Y","","385","25","44.2292","-78.4583","");
STATION ("382","LQ","Lyndy","MA","USA","","N","1040","1043","","42.4375","-70.9583","");
STATION ("382","XU","London","ON","CAN","10.2","Y","","391","50","43.1042","-81.2083","");
STATION ("382","YPL","Pickle Lake","ON","CAN","9.8","Y","412","403","1000","51.4375","-90.2083","");
STATION ("385","HYX","Saginaw","MI","USA","","N","","1010","25","43.4375","-83.875","fast, continuous ID");
STATION ("385","ZDH","Toronto","ON","CAN","","Y","","395","50","43.7292","-79.5417","Was X-385");
STATION ("388","H7","Manitoulin","ON","CAN","10.5","Y","","398","25","45.8542","-81.875","");
STATION ("388","RNW","Chocowinity","NC","USA","","N","","1021","25","35.5208","-77.125","");
STATION ("390","JT","Stephenville","NL","CAN","","Y","","400","450","48.5625","-58.7917","");
STATION ("391","CM","Sumie","OH","USA","","N","1140","1031","","39.9792","-82.7917","");
STATION ("391","DDP","Dorado","PR","PTR","","N","1020","1020","3000","18.4792","-66.375","2kW rptd; 200\' vert;");
STATION ("391","OO","Oshawa","ON","CAN","10.2","Y","","394","7","43.9375","-78.875","11W rptd");
STATION ("392","ML","Charlevoix","QC","CAN","10.2","Y","","400","500","47.6042","-70.2917","");
STATION ("394","YB","North Bay","ON","CAN","","Y","","427","150","46.3958","-79.4583","1kW rptd; 124\' vert.");
STATION ("395","XEN","Xenia","OH","USA","5.7","N","1090","1060","25","39.7292","-83.9583","fast ID");
STATION ("397","ZHA","Hamilton","ON","CAN","10.0","Y","","399","14","43.1875","-80.0417","");
STATION ("398","ZQG","Windsor","ON","CAN","","Y","","386","25","42.2292","-83.0417","Was ~1020Hz");
STATION ("400","CI","Sault Ste. Marie","MI","USA","","N","1052","1018","25","46.3125","-84.5417","");
STATION ("401","YPO","Peawanuck","ON","CAN","10.3","Y","","401","125","54.9792","-85.4583","");
STATION ("403","ZTO","Toronto","ON","CAN","10.5","Y","","400","40","43.7292","-79.7083","");
STATION ("408","SN","St. Catharines","ON","CAN","10.8","Y","","395","14","43.1458","-79.2917","12.5 watts mod/8 watts unmod");
STATION ("414","BC","Baie Comeau","QC","CAN","","Y","","386","500","49.1042","-68.2917","");
STATION ("417","HHG","Huntington","IN","USA","","N","1021","1015","25","40.8542","-85.4583","");
STATION ("419","RYS","Grosse Ile","MI","USA","","N","1009","1025","25","42.1042","-83.125","2X sdb harmonic rptd");
STATION ("423","PCW","Port Clinton","OH","USA","","N","1025","1021","25","41.5208","-82.875","");
STATION ("516","YWA","Petawawa","ON","CAN","","Y","1050","1001","25","45.8958","-77.2917","");
