// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      stations.js                                          *
// * Generated by:  REU                                                  *
// *                                                                     *
// * This is a user editable file containing actual log data.            *
// *                                                                     *
// * Put station details in the following format:                        *
// * STATION(khz,call,qth,ste,cnt,cyc,daid,lsb,usb,pwr,lat,lon,notes);   *
// *                                                                     *
// * Each field should be enclosed with quotes and set to "" if unknown. *
// * For any given signal:                                               *
// *   KHz     is the frequency of the carrier;                          *
// *   call    is the callsign -                                         *
// *           Indicate DGPS Idents with # before station ident number   *
// *   qth     is the town in which the signal is located;               *
// *   ste     is the state or province abbreviation (eg MI = Michigan)  *
// *           or "" if not applicable (e.g. Bahamas)                    *
// *   cnt     is the NDB List approved country code;                    *
// *   cyc     is the number of seconds between repetitions of the call  *
// *   daid    stands for 'Dash after ID' and is either "Y" or "N"       *
// *   lsb     is the offset of the lower sideband from the carrier      *
// *           (Note Canadian NDBs are USB only, for these set to "")    *
// *   usb     is the offset of the upper sideband from the carrier      *
// *   pwr     is the power in watts of the transmitter                  *
// *   lat     is the decimal latitude value (S values are negative)     *
// *   lon     is the decimal longitude value (W values are negative)    *
// *   notes   These notes will show with each logging of the station.   *
// ***********************************************************************

STATION ("263","QY","Sydney","NS","CAN","","N","","400","500","46.2292","-59.9583","");
STATION ("270","FLO","Santa Cruz Das Flores","","AZR","8.45","N","1004","1037","","39.4375","-31.2083","");
STATION ("274","SAL","Sal Island / Amilcar Cabral","","CPV","9.90","Y","0","9","3000","16.6875","-22.9583","");
STATION ("280","QX","Gander","NL","CAN","","N","","400","1000","48.9792","-54.7083","+386 Hz rptd");
STATION ("284","#430","Mizen Head","","IRL","","N","","","","51.4375","-9.7917","DGPS; Ref ID: 660/661; 100 bps");
STATION ("285","#350","Cabo Machicharo","","ESP","","N","","0","","43.4375","-2.7083","DGPS; Ref ID: 500; 100 bps");
STATION ("285.5","#443","Earls Hill / Stirling","","SCT","","N","","","","56.0625","-4.0417","DGPS; Ref ID: 693; 100 bps");
STATION ("287.5","#343","Porto Santo","","MDR","","N","","","","33.0625","-16.375","DGPS; Ref ID: 486/487; 200 bps");
STATION ("288.5","#435","Tory Island Lt.","","IRL","","N","","","","55.2708","-8.2083","DGPS; Ref ID: 670/671; 100bps");
STATION ("289","#351","Cabo Mayor","","ESP","","N","","","","43.3958","-4.375","DGPS; Ref ID: 502; 100bps");
STATION ("290","#452","Blavandshuk Lt","","DNK","","N","","","","55.5625","8.125","DGPS; Ref ID: 705/706; 100 bps");
STATION ("290.5","#447","Flamborough Head Lt.","","ENG","","N","","","","54.1458","-0.125","DGPS; Ref ID: 687/697; 100bps");
STATION ("291","#439","Wormleighton","","ENG","","N","","","","52.1875","-1.375","DGPS; Ref ID: 691; 100bps");
STATION ("291.5","#445","Sumburgh Head","","SHE","","N","","","","59.8542","-1.2917","DGPS; Ref ID: 685/695; 100bps");
STATION ("292","#460","Holmsjö","","SWE","","N","","","","56.4375","15.625","DGPS; Ref ID: 720; 100bps");
STATION ("293","#432","Loop Head Lt.","","IRL","","N","","","","52.5625","-9.9583","DGPS; Ref ID: 665/666; 100bps");
STATION ("293.5","#400","Porkkala Pilot Station","","FIN","","N","","","","59.9792","24.375","DGPS; Ref ID: 600; 100bps");
STATION ("294","#428","Vlieland Lt","","HOL","","N","","","","53.3125","5.0417","DGPS; Ref ID: 655/656; 100bps");
STATION ("295","#352","Cabo Penas","","ESP","","N","","","","43.6458","-5.875","DGPS; Ref ID: 504; 100bps");
STATION ("295.5","#444","Butt Of Lewis","","SCT","","N","","","","58.5208","-6.2917","DGPS; Ref ID: 684/694; 100bps");
STATION ("296","#354","Cabo Finisterre","","ESP","","N","","","","42.8958","-9.2917","DGPS; Ref ID: 508; 100bps (+ #352)");
STATION ("296","#453","Skagen West Lt","","DNK","","N","","","","57.7708","10.625","DGPS; Ref ID: 710/711; 100 bps");
STATION ("296.5","#469","Gothenburg","","SWE","","N","","","","57.6042","11.9583","DGPS; Ref ID: 736; 100bps");
STATION ("297","#446","Girdle Ness","","SCT","","N","","","","57.1458","-2.0417","DGPS; Ref ID: 686/696; 100bps");
STATION ("297.5","#442","Point Lynas Lt.","","WLS","","N","","","","53.4375","-4.2917","DGPS; Ref ID: 682/692; 100bps");
STATION ("298","#468","Nynäshavn","","SWE","","N","","8","","58.9375","17.9583","DGPS; Ref ID: 734; 100bps");
STATION ("298.5","#492","Dune Helgoland","","DEU","","N","","","","54.1875","7.875","DGPS; Ref ID: 762; 100 bps");
STATION ("299","#330","Gatteville","","FRA","","N","","","","49.6875","-1.2917","DGPS; Ref ID: 460; 100 bps");
STATION ("299.5","#463","Skutskar","","SWE","","N","","","","60.6042","17.4583","DGPS; Ref ID: 726; 100 bps");
STATION ("301","#462","Gilze Rijen","","HOL","","N","","","","51.6042","4.9583","");
STATION ("301.5","#404","Turku","","FIN","","N","","4","","60.4375","22.2083","DGPS; Ref ID: 604; 100 bps");
STATION ("302","#467","Hjortens Udde","","SWE","","N","","","","58.6458","12.625","DGPS; Ref ID: 733; 100 bps");
STATION ("302.5","#508","Svinoey Lt.","","NOR","","N","","","","62.3542","5.2917","DGPS; Ref ID: 788/818; 100 bps");
STATION ("303.5","#493","Zeven","","DEU","","N","","","","53.2708","9.2917","DGPS; Ref ID: 763; 100 bps");
STATION ("304","#503","Lista","","NOR","","N","","","","58.1042","6.5417","DGPS; Ref ID: 783/813; 100 bps");
STATION ("304.5","#535","Klaipeda Rear Lt.","","LTU","","N","","","","55.7292","21.125","DGPS; Ref ID: 535; 200 bps");
STATION ("305.5","#341","Sagres","","POR","","N","","1","","37.0208","-8.9583","DGPS; Ref ID: 482/483; 200 bps");
STATION ("307","#530","Ristna Lt.","","EST","","N","","","","58.9375","22.0417","DGPS; Ref ID: 840; 100 bps");
STATION ("307.5","#440","St Catherines Pt Lt","","ENG","","N","","","","50.5625","-1.2917","DGPS; Ref ID: 680/690; 100 bps");
STATION ("307.5","#464","Kapellskar Lt.","","SWE","","N","","","","59.7292","19.125","DGPS; Ref ID: 728; 100 bps");
STATION ("308","#342","Horta","","AZR","","N","","","","38.5208","-28.625","");
STATION ("308.5","#332","Pont Du Buis","","FRA","","N","","","","48.3125","-4.0417","DGPS; Ref ID: 462; 100 bps; May have replaced Cap st Mathieu");
STATION ("309.5","#449","Nash Point","","WLS","","N","","","","51.3958","-3.5417","DGPS; Ref ID: 689/699; 100 bps");
STATION ("310","#336","Cap Ferret","","FRA","","N","","","","44.5625","-1.2083","DGPS; Ref ID: 466; 100 bps");
STATION ("310.5","#500","Faerder Lt.","","NOR","","N","","","","59.0208","10.5417","DGPS; Ref ID: 780/810; 100 bps");
STATION ("311.5","#340","Cabo Carvoeiro Lt","","POR","","N","","0","","39.3542","-9.375","DGPS; Ref ID: 480/481; 200 bps");
STATION ("312.5","#425","Hoek Van Holland","","HOL","","N","","","","51.9792","4.125","DGPS; Ref ID: 650/651; 200 bps");
STATION ("313.5","#366","Cabo San Sebastian","","ESP","","N","","","","41.8958","3.2083","DGPS; Ref ID: 532; 100 bps");
STATION ("313.5","#496","Mauken","","DEU","","N","","","","51.7292","12.7917","DGPS; Ref ID: 766; 100 bps");
STATION ("314","#507","Utvaer Lt.","","NOR","","N","","","","61.0208","4.5417","DGPS; Ref ID: 787/817; 100 bps");
STATION ("316","OE","Dublin","","IRL","8.48","N","380","420","","53.4375","-6.4583","Also heard as OE e");
STATION ("319","VAR","Stavanger / Sola / Varhaug","","NOR","8.09","N","386","417","25","58.6458","5.625","");
STATION ("326","RSH","Dublin / Rush","","IRL","","N","400","400","","53.5208","-6.125","");
STATION ("327","POR","Porto","","POR","8","N","1020","1015","","41.3542","-8.7083","");
STATION ("328","CL","Carlisle	","","ENG","8.6","N","399","400","","54.9375","-2.7917","");
STATION ("328.5","EGT","Londonderry / Eglinton","","NIR","5.26","N","389","390","","55.0625","-7.125","");
STATION ("330","NSM","Inishmaan Isl.	","","IRL","4.77","N","","367","","53.0625","-9.5417","");
STATION ("331","GLW","Glasgow	","","SCT","6.45","N","400","399","","55.8542","-4.4583","");
STATION ("332","OY","Belfast / Aldergrove","","NIR","10.8","N","382","413","","54.6875","-6.125","");
STATION ("334","GMN","Gormanston	","","IRL","","N","394","390","","53.6458","-6.2083","");
STATION ("335","SCO","Amerada Hess / Scott Platform","","XOE","9.58","N","402","421","","58.2708","0.2083","");
STATION ("336","AQ","Aberdeen	","","SCT","","N","400","391","","57.1458","-2.375","");
STATION ("337","MY","Myggenaes","","FRO","","N","448","388","","62.1042","-7.625","");
STATION ("338","PST","Porto Santo / Ilheu De Baixo","","MDR","","N","1020","1025","2000","33.0625","-16.375","");
STATION ("339","BIA","Bournemouth","","ENG","9","N","416","440","40","50.7708","-1.875","");
STATION ("340","HAW","Hawarden","","WLS","10","N","385","414","","53.1875","-2.9583","");
STATION ("341","EDN","Edinburgh	","","SCT","","N","402","392","","55.9792","-3.2917","");
STATION ("350","GLG","Glasgow","","SCT","","N","","","","55.9375","-4.375","INACTIVE");
STATION ("350","LAA","Oulu / Laanila","","FIN","","N","400","410","","64.9792","25.2083","");
STATION ("352","NT","Newcastle","","ENG","","N","422","391","","55.0625","-1.625","");
STATION ("355","PIK","Prestwick	","","SCT","","N","400","400","","55.5208","-4.5417","");
STATION ("371","MGL","Ponta Delgada  (Sao Miguel Island)","","AZR","8.31","N","1019","1051","","37.7292","-25.625","");
STATION ("378","KLY","Killiney for Dublin","","IRL","","N","402","422","","53.2708","-6.125","");
STATION ("380","CAC","Caceres","","ESP","6.75","N","1020","1026","","39.5208","-6.4583","EX CCS");
STATION ("385","WL","Barrow / Walney Isl","","ENG","6","N","385","413","","54.1458","-3.2917","");
STATION ("390","JT","Stephenville","NL","CAN","","Y","","415","450","48.5625","-58.7917","");
STATION ("518","$01E","Niton","","ENG","","N","","","","50.5625","-1.2917","BCST @ 0040, 0440, 0840, 1240, 1640, 2040 UTC; Callsign GNI");
STATION ("518","$01G","Cullercoats","","ENG","","N","","","","55.0208","-1.4583","BCST @ 0100, 0500, 0900, 1300, 1700, 2100 UTC; Callsign GCC");
STATION ("518","$01L","Rogaland","","NOR","","N","0","0","","58.6458","5.625","BCST @ 0150, 0550, 0950, 1350, 1750, 2150 UTC; Callsign LGQ");
STATION ("518","$01O","Portpatrick","","SCT","","N","0","0","","54.8542","-5.125","BCST @ 0220, 0620, 1020, 1420, 1820, 2220 UTC; Callsign GPK");
STATION ("518","$01P","Netherlands (Den Helder)","","HOL","","N","0","0","","52.9375","4.7917","BCST @ 0230, 0630, 1030, 1430, 1830, 2230 UTC; Callsign PBK");
STATION ("518","$01Q","Malin Head","","IRL","","N","","","","55.3542","-7.375","BCST @ 0240, 0640, 1040, 1440, 1840, 2240 UTC; Callsign EJM");
STATION ("518","$01W","Valentia","","IRL","","N","","","","51.9375","-10.375","BCST @ 0340, 0740, 1140, 1540, 1940, 2340 UTC; Callsign EJK");
STATION ("518","$02A","Corsen","","FRA","","N","","","","48.4375","-4.7917","BCST @ 0000, 0400, 0800, 1200, 1600, 2000 UTC; Callsign FRC");
STATION ("341","EDN","Edinburgh	"," ","SCT","7.39","N","405","392"," ","55.9783333333333","-3.28527777777778"," ");
STATION ("347.5","TD","Teeside"," ","ENG","10.48","N","413","407"," ","54.5602777777778","-1.33333333333333"," ");
STATION ("348","ATF","Aberdeen / Dyce"," ","SCT","7.72","N","398","405","25","57.0775","-2.10555555555556"," ");
STATION ("349.5","LPL","LIVERPOOL"," ","ENG","6.96","N","391","432","","53.3394444444444","-2.725"," ");
STATION ("352","ENS","ENNIS"," ","IRL","3.89","N","398","386","","52.905","-8.9275"," ");
STATION ("352","NT","Newcastle"," ","ENG","10.67","N","423","393"," ","55.0502777777778","-1.6425"," ");
STATION ("359","RWY","ISLE OF MAN"," ","IOM","10.02","N","401","399","20","54.0808333333333","-4.62972222222222"," ");
STATION ("368","UW","Edinburgh"," ","SCT","8.28","N","375","423"," ","55.905","-3.5025"," ");
STATION ("368","WTD","Waterford"," ","IRL","5.45","N","397","400"," ","52.1888888888889","-7.08333333333333"," ");
STATION ("368.5","WHI","WHITEGATE"," ","ENG","5.45","N","404","402","25","53.185","-2.62305555555556"," ");
STATION ("374","CBN","Cumbernauld"," ","SCT","5.83","N","393","396"," ","55.9755555555556","-3.97472222222222"," ");
STATION ("518","$01B","Bodø - Lgp"," ","NOR"," ","N"," "," "," ","67.2669444444444","14.3827777777778","BCST @ 0010, 0410, 0810, 1210, 1610, 2010 UTC; Callsign LGP");
STATION ("518","$01K","Niton - Gni (cherbrg)"," ","ENG"," ","N"," "," "," ","50.5830555555556","-1.3","BCST @ 0140, 0540, 0940, 1340, 1740, 2140 UTC; Callsign GNI");
STATION ("518","$01T","Oostende - Ost"," ","BEL"," ","N"," "," "," ","51.1827777777778","2.8","BCST @ 0310, 0710, 1110, 1510, 1910, 2310 UTC; Callsign OST");
STATION ("518","$01U","Tallin - Esa"," ","EST"," ","N"," "," "," ","59.5","24.5","BCST @ 0320, 0720, 1120, 1520, 1920, 2320 UTC; Callsign ESA");
STATION ("518","$02R","Monsanto - Ctv251"," ","POR"," ","N"," "," "," ","38.7327777777778","-9.18277777777778","BCST @ 0250, 0650, 1050, 1450, 1850, 2250 UTC; Callsign CTV-251");
STATION ("518","$03I","Gothenburg (Grimeton)"," ","SWE","","N","","","","57.1041666666667","12.375","BCST@ 0120, 0520, 0920, 1320, 1720, 2120 UTC Callsign: SAG New ID since 01/12/2004");
STATION ("518","$03W","Astrakhan"," ","RUS","","N","","","","46.3125","47.9580555555556","BCST @ 0340, 0740, 1140, 1540, 1940, 2340 UTC; Callsign UJB");
STATION ("518","$03W;2","La Garde (Toulon)"," ","FRA","","N","","","","43.1041666666667","5.95805555555556","BCST @ 0340, 0740, 1140, 1540, 1940, 2340 UTC; Callsign FRL");
STATION ("518","$03X","Cabo de la Nao (Valencia)"," ","ESP","","N","","","","38.7291666666667",".124722222222223","BCST @ 0350, 0750, 1150, 1550, 1950, 2350 UTC; Callsign EAV");
STATION ("384","SLG","SLIGO"," ","IRL","8.19","N","405","408","U","54.2780555555556","-8.59972222222222"," ");
STATION ("387","CML","Clonmel"," ","IRL","5.03","N","418","409","50","52.4536111111111","-7.48"," ");
STATION ("388.5","CDF","CARDIFF"," ","ENG","7.87","N","385","407","","51.3933333333333","-3.33666666666667"," ");
STATION ("394","DND","Dundee"," ","SCT","5.74","N","414","376"," ","56.455","-3.11472222222222"," ");
STATION ("395","FOY","Foynes"," ","IRL","6.18","N","396","404","50","52.5661111111111","-9.19527777777778"," ");
STATION ("395","LAY","Islay"," ","SCT","6.47","N","402","399"," ","55.6827777777778","-6.24916666666667"," ");
STATION ("397","OP","Dublin"," ","IRL","9.77","N","403","402","15","53.4136111111111","-6.13833333333333"," ");
STATION ("399","NGY","New Galloway"," ","SCT","6.41","N","416","392","80","55.1775","-4.16861111111111"," ");
STATION ("407","GAR","Garristown"," ","IRL","5.45","N","428","368","50","53.5286111111111","-6.44722222222222"," ");
STATION ("420","BPL","Blackpool"," ","ENG","7.87","N","370","412","","53.7733333333333","-3.02666666666667"," ");
STATION ("420","HB","Belfast Harbour"," ","NIR","7.26","N","407","386","","53.615","-5.88166666666667"," ");
STATION ("426","PW","Prestwick"," ","SCT","5.05","N","407","403"," ","55.5441666666667","-4.68138888888889"," ");
STATION ("518","$01J","Karlskrona (Gislövshammer)"," ","SWE"," ","N"," "," "," ","55.4827777777778","14.3158333333333","BCST @ 0130, 0530, 0930, 1330, 1730, 2130 UTC; Callsign SAH");
STATION ("518","$03Q","Split"," ","BIH","","N","","","","43.5205555555556","16.4580555555556","BCST @ 0240, 0640, 1040, 1440, 1840, 2240 UTC; Callsign 9AS");
