// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      log.js                                               *
// * Generated by:  RWW                                                  *
// *                                                                     *
// * This is a user editable file containing actual log data.            *
// *                                                                     *
// * Put logged station details in the following format:                 *
// * LOG ("KHz","Call","YYYYMMDD","HHMM","Optional notes on reception"); *
// *                                                                     *
// * If any logged station doesn't appear in stations.js, you will see   *
// * an error message. Add new stations to the file stations.js          *
// * Don't use "quotes" in the notes field - single 'quotes' are fine.   *
// ***********************************************************************

LOG ("302","BN","20051027","0251","");
LOG ("359","AMB","20051027","0303","");
LOG ("374","BML","20051027","0311","");
LOG ("380","MC","20051027","0321","");
LOG ("392","KCY","20051027","0329","");
LOG ("278","CG","20051027","0349","");
LOG ("294","#707","20051027","0349","");
LOG ("419","AF","20051027","0352","");
LOG ("332","CAS","20051027","1245","");
LOG ("389","GFN","20051027","1255","");
LOG ("315","#704","20051027","1300","");
LOG ("313","#706","20051027","1346","");
LOG ("284","GAY","20051027","1347","");
LOG ("374","BML","20051029","1432","");
LOG ("371","HUG","20051029","1437","");
LOG ("377","ROM","20051029","1459","");
LOG ("380","MC","20051029","1523","");
LOG ("383","HM","20051029","1536","");
