// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      stations.js                                          *
// * Generated by:  RWW                                                  *
// *                                                                     *
// * This is a user editable file containing actual log data.            *
// *                                                                     *
// * Put station details in the following format:                        *
// * STATION(khz,call,qth,ste,cnt,cyc,daid,lsb,usb,pwr,lat,lon,notes);   *
// *                                                                     *
// * Each field should be enclosed with quotes and set to "" if unknown. *
// * For any given signal:                                               *
// *   KHz     is the frequency of the carrier;                          *
// *   call    is the callsign -                                         *
// *           Indicate DGPS Idents with # before station ident number   *
// *   qth     is the town in which the signal is located;               *
// *   ste     is the state or province abbreviation (eg MI = Michigan)  *
// *           or "" if not applicable (e.g. Bahamas)                    *
// *   cnt     is the NDB List approved country code;                    *
// *   cyc     is the number of seconds between repetitions of the call  *
// *   daid    stands for 'Dash after ID' and is either "Y" or "N"       *
// *   lsb     is the offset of the lower sideband from the carrier      *
// *           (Note Canadian NDBs are USB only, for these set to "")    *
// *   usb     is the offset of the upper sideband from the carrier      *
// *   pwr     is the power in watts of the transmitter                  *
// *   lat     is the decimal latitude value (S values are negative)     *
// *   lon     is the decimal longitude value (W values are negative)    *
// *   notes   These notes will show with each logging of the station.   *
// ***********************************************************************

STATION ("278","CG","Coolangatta","QD","AUS","8.6","N","1027","1020","","-28.1458","153.542","");
STATION ("284","GAY","Gayndah","QD","AUS","9.8","N","1046","1037","","-25.6042","151.708","");
STATION ("294","#707","Brisbane","QD","AUS","","N","","","180","-27.1042","153.042","DGPS; Ref ID: 7; 200bps");
STATION ("302","BN","Brisbane","QD","AUS","9.75","N","1031","1019","","-27.3958","153.125","");
STATION ("313","#706","Gladstone","QD","AUS","","N","","","320","-24.0208","151.042","DGPS; Ref ID:6; 200bps");
STATION ("315","#704","Mackay","QD","AUS","","N","","","289","-21.1042","149.208","DGPS; Ref ID:4; 200bps");
STATION ("332","CAS","Casino","NW","AUS","9.1","N","407","400","50","-28.8542","153.042","");
STATION ("359","AMB","Amberley","QD","AUS","12.3","N","404","404","2000","-27.6458","152.708","Carries weather information");
STATION ("371","HUG","HUGHENDEN","QD","AUS","9.95","N","1029","1022","","-20.8125","144.208","");
STATION ("374","BML","Bromelton","QD","AUS","10.1","N","423","403","","-27.9792","152.875","");
STATION ("377","ROM","Roma","QD","AUS","9.75","N","1045","","","-26.5625","148.792","");
STATION ("380","MC","Maroochydore","QD","AUS","9.8","N","1013","1019","","-26.6042","153.125","");
STATION ("383","HM","HAMILTON ISLAND","QD","AUS","8.8","N","","1014","","-20.3542","148.958","");
STATION ("389","GFN","GRAFTON","NW","AUS","9.5","N","402","400","","-29.7708","153.042","");
STATION ("392","KCY","Kilcoy","QD","AUS","10.0","N","1023","1013","","-26.9375","152.542","");
STATION ("419","AF","Archerfield","QD","AUS","29.0","N","400","400","","-27.5625","153.042","Carries weather information");
