// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      config.js                                            *
// * Generated by:  RWW                                                  *
// *                                                                     *
// * This is a user editable file with details on the logbook's owner.   *
// ***********************************************************************

qth_lat =    -26.2708;
qth_lon =    27.9583;
qth_name =   "Martin Francis, Johannesburg (Remote), AFS";
qth_email =  "martin@classaxe.com";
qth_home =   "http://www.classaxe.com/dx";
monthly =    1;
utc_offset = 2;
