// ***********************************************************************
// * FILE HEADER:                                                        *
// ***********************************************************************
// * Filename:      stations.js                                          *
// * Generated by:  REU                                                  *
// *                                                                     *
// * This is a user editable file containing actual log data.            *
// *                                                                     *
// * Put station details in the following format:                        *
// * STATION(khz,call,qth,ste,cnt,cyc,daid,lsb,usb,pwr,lat,lon,notes);   *
// *                                                                     *
// * Each field should be enclosed with quotes and set to "" if unknown. *
// * For any given signal:                                               *
// *   KHz     is the frequency of the carrier;                          *
// *   call    is the callsign -                                         *
// *           Indicate DGPS Idents with # before station ident number   *
// *   qth     is the town in which the signal is located;               *
// *   ste     is the state or province abbreviation (eg MI = Michigan)  *
// *           or "" if not applicable (e.g. Bahamas)                    *
// *   cnt     is the NDB List approved country code;                    *
// *   cyc     is the number of seconds between repetitions of the call  *
// *   daid    stands for 'Dash after ID' and is either "Y" or "N"       *
// *   lsb     is the offset of the lower sideband from the carrier      *
// *           (Note Canadian NDBs are USB only, for these set to "")    *
// *   usb     is the offset of the upper sideband from the carrier      *
// *   pwr     is the power in watts of the transmitter                  *
// *   lat     is the decimal latitude value (S values are negative)     *
// *   lon     is the decimal longitude value (W values are negative)    *
// *   notes   These notes will show with each logging of the station.   *
// ***********************************************************************

STATION ("263","QY","Sydney","NS","CAN","","N","","400","500","46.2292","-59.9583","");
STATION ("270","FLO","Santa Cruz Das Flores","","AZR","8.45","N","1004","1037","","39.4375","-31.2083","");
STATION ("274","SAL","Sal Island / Amilcar Cabral","","CPV","9.90","Y","0","9","3000","16.6875","-22.9583","");
STATION ("280","QX","Gander","NL","CAN","","N","","400","1000","48.9792","-54.7083","+386 Hz rptd");
STATION ("284","#430","Mizen Head","","IRL","","N","","","","51.4375","-9.7917","DGPS; Ref ID: 660/661; 100 bps");
STATION ("285","#350","Cabo Machicharo","","ESP","","N","","0","","43.4375","-2.7083","DGPS; Ref ID: 500; 100 bps");
STATION ("285.5","#443","Earls Hill / Stirling","","SCT","","N","","","","56.0625","-4.0417","DGPS; Ref ID: 693; 100 bps");
STATION ("287.5","#343","Porto Santo","","MDR","","N","","","","33.0625","-16.375","DGPS; Ref ID: 486/487; 200 bps");
STATION ("288.5","#435","Tory Island Lt.","","IRL","","N","","","","55.2708","-8.2083","DGPS; Ref ID: 670/671; 100bps");
STATION ("289","#351","Cabo Mayor","","ESP","","N","","","","43.3958","-4.375","DGPS; Ref ID: 502; 100bps");
STATION ("290","#452","Blavandshuk Lt","","DNK","","N","","","","55.5625","8.125","DGPS; Ref ID: 705/706; 100 bps");
STATION ("290.5","#447","Flamborough Head Lt.","","ENG","","N","","","","54.1458","-0.125","DGPS; Ref ID: 687/697; 100bps");
STATION ("291","#439","Wormleighton","","ENG","","N","","","","52.1875","-1.375","DGPS; Ref ID: 691; 100bps");
STATION ("291.5","#445","Sumburgh Head","","SHE","","N","","","","59.8542","-1.2917","DGPS; Ref ID: 685/695; 100bps");
STATION ("292","#460","Holmsjö","","SWE","","N","","","","56.4375","15.625","DGPS; Ref ID: 720; 100bps");
STATION ("293","#432","Loop Head Lt.","","IRL","","N","","","","52.5625","-9.9583","DGPS; Ref ID: 665/666; 100bps");
STATION ("293.5","#400","Porkkala Pilot Station","","FIN","","N","","","","59.9792","24.375","DGPS; Ref ID: 600; 100bps");
STATION ("294","#428","Vlieland Lt","","HOL","","N","","","","53.3125","5.0417","DGPS; Ref ID: 655/656; 100bps");
STATION ("295","#352","Cabo Penas","","ESP","","N","","","","43.6458","-5.875","DGPS; Ref ID: 504; 100bps");
STATION ("295.5","#444","Butt Of Lewis","","SCT","","N","","","","58.5208","-6.2917","DGPS; Ref ID: 684/694; 100bps");
STATION ("296","#354","Cabo Finisterre","","ESP","","N","","","","42.8958","-9.2917","DGPS; Ref ID: 508; 100bps (+ #352)");
STATION ("296","#453","Skagen West Lt","","DNK","","N","","","","57.7708","10.625","DGPS; Ref ID: 710/711; 100 bps");
STATION ("296.5","#469","Gothenburg","","SWE","","N","","","","57.6042","11.9583","DGPS; Ref ID: 736; 100bps");
STATION ("297","#446","Girdle Ness","","SCT","","N","","","","57.1458","-2.0417","DGPS; Ref ID: 686/696; 100bps");
STATION ("297.5","#442","Point Lynas Lt.","","WLS","","N","","","","53.4375","-4.2917","DGPS; Ref ID: 682/692; 100bps");
STATION ("298","#468","Nynäshavn","","SWE","","N","","8","","58.9375","17.9583","DGPS; Ref ID: 734; 100bps");
STATION ("298.5","#492","Dune Helgoland","","DEU","","N","","","","54.1875","7.875","DGPS; Ref ID: 762; 100 bps");
STATION ("299","#330","Gatteville","","FRA","","N","","","","49.6875","-1.2917","DGPS; Ref ID: 460; 100 bps");
STATION ("299.5","#463","Skutskar","","SWE","","N","","","","60.6042","17.4583","DGPS; Ref ID: 726; 100 bps");
STATION ("301","#462","Gilze Rijen","","HOL","","N","","","","51.6042","4.9583","");
STATION ("301.5","#404","Turku","","FIN","","N","","4","","60.4375","22.2083","DGPS; Ref ID: 604; 100 bps");
STATION ("302","#467","Hjortens Udde","","SWE","","N","","","","58.6458","12.625","DGPS; Ref ID: 733; 100 bps");
STATION ("302.5","#508","Svinoey Lt.","","NOR","","N","","","","62.3542","5.2917","DGPS; Ref ID: 788/818; 100 bps");
STATION ("303.5","#493","Zeven","","DEU","","N","","","","53.2708","9.2917","DGPS; Ref ID: 763; 100 bps");
STATION ("304","#503","Lista","","NOR","","N","","","","58.1042","6.5417","DGPS; Ref ID: 783/813; 100 bps");
STATION ("304.5","#535","Klaipeda Rear Lt.","","LTU","","N","","","","55.7292","21.125","DGPS; Ref ID: 535; 200 bps");
STATION ("305.5","#341","Sagres","","POR","","N","","1","","37.0208","-8.9583","DGPS; Ref ID: 482/483; 200 bps");
STATION ("307","#530","Ristna Lt.","","EST","","N","","","","58.9375","22.0417","DGPS; Ref ID: 840; 100 bps");
STATION ("307.5","#440","St Catherines Pt Lt","","ENG","","N","","","","50.5625","-1.2917","DGPS; Ref ID: 680/690; 100 bps");
STATION ("307.5","#464","Kapellskar Lt.","","SWE","","N","","","","59.7292","19.125","DGPS; Ref ID: 728; 100 bps");
STATION ("308","#342","Horta","","AZR","","N","","","","38.5208","-28.625","");
STATION ("308.5","#332","Pont Du Buis","","FRA","","N","","","","48.3125","-4.0417","DGPS; Ref ID: 462; 100 bps; May have replaced Cap st Mathieu");
STATION ("309.5","#449","Nash Point","","WLS","","N","","","","51.3958","-3.5417","DGPS; Ref ID: 689/699; 100 bps");
STATION ("310","#336","Cap Ferret","","FRA","","N","","","","44.5625","-1.2083","DGPS; Ref ID: 466; 100 bps");
STATION ("310.5","#500","Faerder Lt.","","NOR","","N","","","","59.0208","10.5417","DGPS; Ref ID: 780/810; 100 bps");
STATION ("311.5","#340","Cabo Carvoeiro Lt","","POR","","N","","0","","39.3542","-9.375","DGPS; Ref ID: 480/481; 200 bps");
STATION ("312.5","#425","Hoek Van Holland","","HOL","","N","","","","51.9792","4.125","DGPS; Ref ID: 650/651; 200 bps");
STATION ("313.5","#366","Cabo San Sebastian","","ESP","","N","","","","41.8958","3.2083","DGPS; Ref ID: 532; 100 bps");
STATION ("313.5","#496","Mauken","","DEU","","N","","","","51.7292","12.7917","DGPS; Ref ID: 766; 100 bps");
STATION ("314","#507","Utvaer Lt.","","NOR","","N","","","","61.0208","4.5417","DGPS; Ref ID: 787/817; 100 bps");
STATION ("316","OE","Dublin","","IRL","8.48","N","380","420","","53.4375","-6.4583","Also heard as OE e");
STATION ("319","VAR","Stavanger / Sola / Varhaug","","NOR","8.09","N","386","417","25","58.6458","5.625","");
STATION ("326","RSH","Dublin / Rush","","IRL","","N","400","400","","53.5208","-6.125","");
STATION ("327","POR","Porto","","POR","8","N","1020","1015","","41.3542","-8.7083","");
STATION ("328","CL","Carlisle	","","ENG","8.6","N","399","400","","54.9375","-2.7917","");
STATION ("328.5","EGT","Londonderry / Eglinton","","NIR","5.26","N","389","390","","55.0625","-7.125","");
STATION ("330","NSM","Inishmaan Isl.	","","IRL","4.77","N","","367","","53.0625","-9.5417","");
STATION ("331","GLW","Glasgow	","","SCT","6.45","N","400","399","","55.8542","-4.4583","");
STATION ("332","OY","Belfast / Aldergrove","","NIR","10.8","N","382","413","","54.6875","-6.125","");
STATION ("334","GMN","Gormanston	","","IRL","","N","394","390","","53.6458","-6.2083","");
STATION ("335","SCO","Amerada Hess / Scott Platform","","XOE","9.58","N","402","421","","58.2708","0.2083","");
STATION ("336","AQ","Aberdeen	","","SCT","","N","400","391","","57.1458","-2.375","");
STATION ("337","MY","Myggenaes","","FRO","","N","448","388","","62.1042","-7.625","");
STATION ("338","PST","Porto Santo / Ilheu De Baixo","","MDR","","N","1020","1025","2000","33.0625","-16.375","");
STATION ("339","BIA","Bournemouth","","ENG","9","N","416","440","40","50.7708","-1.875","");
STATION ("340","HAW","Hawarden","","WLS","10","N","385","414","","53.1875","-2.9583","");
STATION ("341","EDN","Edinburgh	","","SCT","","N","402","392","","55.9792","-3.2917","");
STATION ("350","GLG","Glasgow","","SCT","","N","","","","55.9375","-4.375","INACTIVE");
STATION ("350","LAA","Oulu / Laanila","","FIN","","N","400","410","","64.9792","25.2083","");
STATION ("352","NT","Newcastle","","ENG","","N","422","391","","55.0625","-1.625","");
STATION ("355","PIK","Prestwick	","","SCT","","N","400","400","","55.5208","-4.5417","");
STATION ("371","MGL","Ponta Delgada  (Sao Miguel Island)","","AZR","8.31","N","1019","1051","","37.7292","-25.625","");
STATION ("378","KLY","Killiney for Dublin","","IRL","","N","402","422","","53.2708","-6.125","");
STATION ("380","CAC","Caceres","","ESP","6.75","N","1020","1026","","39.5208","-6.4583","EX CCS");
STATION ("385","WL","Barrow / Walney Isl","","ENG","6","N","385","413","","54.1458","-3.2917","");
STATION ("390","JT","Stephenville","NL","CAN","","Y","","415","450","48.5625","-58.7917","");
STATION ("518","$01E","Niton","","ENG","","N","","","","50.5625","-1.2917","BCST @ 0040, 0440, 0840, 1240, 1640, 2040 UTC; Callsign GNI");
STATION ("518","$01G","Cullercoats","","ENG","","N","","","","55.0208","-1.4583","BCST @ 0100, 0500, 0900, 1300, 1700, 2100 UTC; Callsign GCC");
STATION ("518","$01L","Rogaland","","NOR","","N","0","0","","58.6458","5.625","BCST @ 0150, 0550, 0950, 1350, 1750, 2150 UTC; Callsign LGQ");
STATION ("518","$01O","Portpatrick","","SCT","","N","0","0","","54.8542","-5.125","BCST @ 0220, 0620, 1020, 1420, 1820, 2220 UTC; Callsign GPK");
STATION ("518","$01P","Netherlands (Den Helder)","","HOL","","N","0","0","","52.9375","4.7917","BCST @ 0230, 0630, 1030, 1430, 1830, 2230 UTC; Callsign PBK");
STATION ("518","$01Q","Malin Head","","IRL","","N","","","","55.3542","-7.375","BCST @ 0240, 0640, 1040, 1440, 1840, 2240 UTC; Callsign EJM");
STATION ("518","$01W","Valentia","","IRL","","N","","","","51.9375","-10.375","BCST @ 0340, 0740, 1140, 1540, 1940, 2340 UTC; Callsign EJK");
STATION ("518","$02A","Corsen","","FRA","","N","","","","48.4375","-4.7917","BCST @ 0000, 0400, 0800, 1200, 1600, 2000 UTC; Callsign FRC");
